### ISSUE TITLE
fix qa build process

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#306]
#303 broke the QA process.

`tagged-commit` is run locally, installs the qa branch of alpheios-core, and  rebuilds the `dist` directory, and tags the release, which then kicks off the travis build that creates the release and the dist directory. However the travis build recreates the dist directory without first installing the qa branch of alpheios-core, and it also creates an invalid build number.

I think we have a bit of a race condition here. I think it might be worth looking into whether switching to use of GitHub actions instead of travis for the release tagging and deployment would allow us to simplify things.  GitHub actions are much more full featured than they were when we setup this new build process.

While looking into this, we might also consider deploying the dist directory of the webextension qa builds to the Alpheios s3 misc-dev bucket, including a fully populated env-webext.js (which is currently excluded from the dist.zip that is packaged with the release as it contains a clientId secret.

**Comment by balmas** [comment]
See also related notes in alpheios-project/documentation#32

**Comment by balmas** [comment]
this is fixed in 
Alpheios Reading Tools 3.3.1 build qa.20200804636

The dist.zip available from the GitHub release now also includes the env-webext.js so you no longer need to copy that in.

I think this obviates the need for a separate deployment of the zip on S3.

**Comment by monzug** [comment]
I am still getting the dist.zip file with env-webext.js from  https://github.com/alpheios-project/webextension/releases/download, is that ok? the build number has been fixed:   Alpheios Reading Tools 3.3.1 build qa.20200804636
Alpheios Components 3.3.0-qa.20200804505

**Comment by balmas** [comment]
Yes that’s correct
