### ISSUE TITLE
En language in wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#331]
I have never seen the en language id in wordlist before yesterday and latest FF builds. Note that this is only for Scaife site.
As soon as I install the new FF build and I do some lookup/double click, the words are saved in wordlist with en language id. Irina, do you have any idea where this en language id comes from, only in Scaife?  is it the page language defined on the site? see attachment below.
as soon as I reset page language to greek or latin in Options, I do not get these errors any longer.

![english](https://user-images.githubusercontent.com/41396793/142443332-04fab6e5-b0fd-4bee-b45f-f443a7634e61.JPG)

by clicking on any word, saved under en language id, I get a bunch of errors.  See below

![greek-data](https://user-images.githubusercontent.com/41396793/142443498-5bb1d17d-a278-452f-b03b-c3a32757dcdf.JPG)

**Comment by irina060981** [comment]
Yes, it has en as a page language.
It is easy to check - open context menu and select **View Page source**

![image](https://user-images.githubusercontent.com/12377640/142507950-20bfc717-5e01-4a3c-8dc9-8fb1a0cf981c.png)

You would see a page in non-rendered mode
![image](https://user-images.githubusercontent.com/12377640/142507999-f304872a-f8c2-46a5-8bd2-f549c73c1498.png)

You could see that it is defined as en =>
<html lang="en">

So it is not a bug, as a page language has priority

**Comment by monzug** [comment]
@Irina, do you remember the issue # about priorities on page language? we
made that change after the release and I have never tested in web extension.

**Comment by irina060981** [comment]
No, I don't remember a number - may be you could search for it in issues list?

**Comment by monzug** [comment]
It might be this one:
https://github.com/alpheios-project/alignment-editor-new/issues/302

**Comment by irina060981** [comment]
Yes, I think you are quite right

**Comment by monzug** [comment]
an other one: https://github.com/alpheios-project/alignment-editor-new/pull/328
but I think this is the one I was looking for: https://github.com/alpheios-project/alpheios-core/issues/639

**Comment by monzug** [comment]
I do not understand why it takes en as language at the first double click, then when I change page language from greek to latin (it's a latin text), all goes well. except in wordlist where words are saved in both en language list and latin language list. there is something not quite right here
![Screen Shot 2021-11-19 at 12 55 10 PM](https://user-images.githubusercontent.com/41396793/142619202-03a09896-5420-4124-8d5d-61d1f5b15664.png)

**Comment by monzug** [comment]
also the show contexts icon is available for words in the en language list but not for same words in the lat language list. see below

![show-context](https://user-images.githubusercontent.com/41396793/142640976-912aa613-33f8-457c-ae07-163030041d1f.JPG)

**Comment by irina060981** [comment]
I described the same problem here 
https://github.com/alpheios-project/webextension/issues/330

**Comment by irina060981** [comment]
Bug is fixed.
New Release  is published.

**Comment by monzug** [comment]
I still see the same issue: words been saved in en and also in the Alpheios page language in wordlist and that the show contexts icon is available for words in the en language list only.
see example of same word repeated 3 times in wordlist: en as page language in scaife, greek as page language in alpheios, latin when I changed the page language to latin.
![Screen Shot 2021-11-22 at 2 42 48 PM](https://user-images.githubusercontent.com/41396793/142872631-ac87fe80-b1f0-4030-8738-9f62b495c488.png)

**Comment by irina060981** [comment]
yes, the same bug is repeated on https://scaife.perseus.org/reader/
It is strange - I will check

**Comment by irina060981** [comment]
I find a small bug in language definition (hope it is last) - now it is fixed and I could not reproduced it any more.

Anyway I would describe what was the source of the problem, may be you could face with some other edge case.

There are two aspects:

1. When an application prepare a word to get morphology dater it creates two objects: one for word information (TextSelector) and one for context information (TextQuoteSelector). Previous bug was in the case when application decides to change word language (according to https://github.com/alpheios-project/alpheios-core/issues/639) , but in fact it changes it only for one object (TextSelctor) but not for the second (TextQuoteSelector) - so application first creates a worditem for one object (TextQuoteSelector) and then for the other (TextSelector). In normal case they would be merged automatically and finally we have one worditem.  So my fix is - now language is updated in both objects.

2. Each object (TextSelector) has two properties for storing language data - one is for plain language name (as is), one for formatted from supported list. (It happened historically, and out team has no time for removing such duplication, but it was in plans - https://github.com/alpheios-project/alpheios-core/issues/6) . And there was a case when a site has defined language that is not from supported list (like en), and that's why application decides to use Page language  and updated only one language value, but the second was still en. And wordlist again registered two different words - on for homonym and one for context - because they use different language properties. - So again my fix - is to update both language objects.

Now I hope I found all bugs of this issue https://github.com/alpheios-project/alpheios-core/issues/639

**Comment by monzug** [comment]
will dig in soon. Hopefully it will be the last one as u said.

**Comment by monzug** [comment]
No more en language. Great. Thanks.

**Comment by monzug** [comment]
Actually, I just experienced this problem in Loeb Classics. in FF/PC I used loebclassic for first time in a really long time. select a latin text, click on few words, check wordlist and I have the words saved in two different language list: la and lat. The la language list  has show context link, while the lat language list has the number of occurancies and the lemmas.
see attachment
![duplicate language](https://user-images.githubusercontent.com/41396793/144036297-35d83343-d3a6-4b2b-a7a5-8460aa205b98.JPG)

**Comment by irina060981** [comment]
It is because the block language is defined as "la" - shorter variant of "lat", that we used

**Comment by monzug** [comment]
Thanks. I figured that la is short def of lat. is there a more general way to prevent similar scenarios from happening?

**Comment by irina060981** [comment]
Such problems are from our using two different forms of language inside (I described it in prebious comments here)
I added normalization for language code - it would work for all similiar cases.

Will upload to releases later

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
tested in FF/PC and Mac. fixed.
